title: "Robocode Tank Royale"
description: "Documentation for the programming game Robocode Tank Royale."
base: /tankroyale/docs/
port: 8080

themeConfig:
  sidebar:
    - title: Introduction
      path: /articles/intro
    - title: Tank Royale
      path: /articles/tank-royale
    - title: Bot Anatomy
      path: /articles/anatomy
    - title: Coordinates and Angles
      path: /articles/coordinates-and-angles
    - title: Physics
      path: /articles/physics
    - title: Scoring
      path: /articles/scoring
    - title: History
      path: /articles/history

plugins:
  vuepress-plugin-mathjax:
    target: svg
    macros:
      "*": ×
