title: "Robocode Tank Royale Docs"
description: "Documentation for the programming game Robocode Tank Royale."
base: /tankroyale/docs/
port: 8080

themeConfig:
  sidebar:
    - title: What is Robocode?
      path: /articles/intro
    - title: API Documentation
      path: /api/apis
    - title: Bot Anatomy
      path: /articles/anatomy
    - title: Coordinates and Angles
      path: /articles/coordinates-and-angles
    - title: Physics
      path: /articles/physics
    - title: Scoring
      path: /articles/scoring
    - title: Tank Royale vs orig. Robocode
      path: /articles/tank-royale
    - title: Robocode history
      path: /articles/history

plugins:
  vuepress-plugin-mathjax:
    target: svg
    macros:
      "*": ×
