[versions]

node-version = "15.5.1"

[libraries]

gson = "com.google.code.gson:gson:2.8.7"
gson-extras = "org.danilopianini:gson-extras:0.2.2"
jansi = "org.fusesource.jansi:jansi:2.3.4"
java-websocket = "org.java-websocket:Java-WebSocket:1.5.2"
jsonschema2pojo = "org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:1.1.1"
kotest-junit5 = "io.kotest:kotest-runner-junit5-jvm:5.0.0.M1"
picocli = "info.picocli:picocli:4.6.1"
proguard-gradle = "com.guardsquare:proguard-gradle:7.1.1"
miglayout-swing = "com.miglayout:miglayout-swing:11.0"
mockk = "io.mockk:mockk:1.12.0"
nv-i18n = "com.neovisionaries:nv-i18n:1.28"
serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0-RC"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.0-alpha5"

[plugins]

hidetake-ssh = "org.hidetake.ssh:2.10.1"
itiviti-dotnet = "com.itiviti.dotnet:1.8.2"
node-gradle = "com.github.node-gradle.node:3.1.0"
