title: Robocode Tank Royale Docs
description: Documentation for the programming game Robocode Tank Royale.
base: /tank-royale/
port: 8080

dest: build/docs

head:
  - - link
    - rel: icon
      href: /favicon.ico
      type: image/x-icon

themeConfig:
  logo:
    /Tank-logo.svg
  sidebar:
    - title: What is Robocode?
      path: /articles/intro
    - title: Installation
      path: /articles/installation
    - title: My First Bot
      path: /tutorial/my-first-bot
    - title: API Documentation
      path: /api/apis
    - title: Debugging
      path: /articles/debug
    - title: Bot Anatomy
      path: /articles/anatomy
    - title: Coordinates and Angles
      path: /articles/coordinates-and-angles
    - title: Physics
      path: /articles/physics
    - title: Scoring
      path: /articles/scoring
    - title: Booter
      path: /articles/booter
    - title: Tank Royale vs orig. Robocode
      path: /articles/tank-royale
    - title: Robocode history
      path: /articles/history

plugins:
  vuepress-plugin-mathjax:
    target: svg
    macros:
      "*": ×
